// Estados de pedido
export const ORDER_STATUS = {
  PENDING: 1,
  CONFIRMED: 2,
  IN_PREPARATION: 3,
  READY_FOR_PICKUP: 4,
  DELIVERED: 5,
  CANCELLED: 6,
};

// Etiquetas para mostrar en la interfaz
export const ORDER_STATUS_LABELS = {
  [ORDER_STATUS.PENDING]: 'Pendiente',
  [ORDER_STATUS.CONFIRMED]: 'Confirmado',
  [ORDER_STATUS.IN_PREPARATION]: 'En Preparación',
  [ORDER_STATUS.READY_FOR_PICKUP]: 'Listo para Retirar',
  [ORDER_STATUS.DELIVERED]: 'Entregado',
  [ORDER_STATUS.CANCELLED]: 'Cancelado',
};

// Colores para los estados
export const ORDER_STATUS_COLORS = {
  [ORDER_STATUS.PENDING]: 'yellow',
  [ORDER_STATUS.CONFIRMED]: 'blue',
  [ORDER_STATUS.IN_PREPARATION]: 'purple',
  [ORDER_STATUS.READY_FOR_PICKUP]: 'green',
  [ORDER_STATUS.DELIVERED]: 'emerald',
  [ORDER_STATUS.CANCELLED]: 'red',
};

// Flujo de estados permitidos
export const ORDER_STATUS_FLOW = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.IN_PREPARATION, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.IN_PREPARATION]: [ORDER_STATUS.READY_FOR_PICKUP],
  [ORDER_STATUS.READY_FOR_PICKUP]: [ORDER_STATUS.DELIVERED],
  [ORDER_STATUS.DELIVERED]: [],
  [ORDER_STATUS.CANCELLED]: [],
}; 