import { PERMISSIONS } from './permissions';

// Roles del sistema (deben coincidir con el backend)
export const ROLES = {
  ADMIN: 'admin',
  VENDEDOR: 'vendedor', 
  CLIENTE: 'cliente',
};

// Etiquetas para mostrar en la interfaz
export const ROLE_LABELS = {
  [ROLES.ADMIN]: 'Administrador',
  [ROLES.VENDEDOR]: 'Vendedor',
  [ROLES.CLIENTE]: 'Cliente',
};

// Permisos por rol
export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_PRODUCTS,
    PERMISSIONS.MANAGE_CATEGORIES,
    PERMISSIONS.MANAGE_SELLERS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.MANAGE_PAYMENT_METHODS,
    PERMISSIONS.MANAGE_ORDER_STATUS,
    PERMISSIONS.VIEW_ALL_ORDERS,
    PERMISSIONS.UPDATE_ORDER_STATUS,
  ],
  [ROLES.VENDEDOR]: [
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.MANAGE_OWN_PRODUCTS,
    PERMISSIONS.VIEW_OWN_ORDERS,
    PERMISSIONS.UPDATE_OWN_ORDER_STATUS,
  ],
  [ROLES.CLIENTE]: [
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.MANAGE_CART,
    PERMISSIONS.PLACE_ORDERS,
    PERMISSIONS.VIEW_OWN_ORDERS,
    PERMISSIONS.MANAGE_PROFILE,
    PERMISSIONS.MANAGE_ADDRESSES,
    PERMISSIONS.CREATE_REVIEWS,
  ],
}; 